### ISSUE TITLE
Katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [apndx/ScentGraph#66]
# Katselmointi

Terve @apndx! Tässä lyhyt katselmointi Full Stack kurssin projektistasi.

### Mitä tein?

- Rekisteröin uuden käyttäjän ja kirjauduin sillä sisään
- Lisäsin uuden hajuveden
- Lisäsin lisäämälleni hajuvedelle muistiinpanon
- Katsoin hajuvesien visualisointia eri hakurajaimilla
- Kirjauduin ulos

### Kokemus

- Selkeä ja tyylikäs käyttöliittymä, hyvää työtä! 🥇
- Rekisteröitymis- ja hajuvesilomake voisi näyttää väärin täytetyissä kentissä virheilmoituksen sen sijaan, että tallennus-painike on poissa käytöstä
- [Etusivulla](https://scentgraph.herokuapp.com/) voisi olla jotain hyödyllistä sisältöä, tai se voisi ohjata suoraan hajuvesien visualisointi sivulle
- Jos hajuvesien visualisoinnin hakurajaimet muuttaisivat selaimen osoiterivin osoitetta esim. [query-parametreja](https://reacttraining.com/react-router/web/example/query-parameters) käyttämällä, niin jokaiseen visualisaatioon voisi luoda pysyvän linkin

## Koodi

- Frontend-puolen koodi on selkeästi organisoitua, hyvä!
- Reactin `PureComponent`-luokan käyttö on tarpeen vain _erittäin_ harvoissa tapauksissa, joissa ylimääräiset renderöinnit aiheuttavat suorituskykyongelmia. Sen laajamittainen käyttö aiheuttaa yleensä enemmän ongelmia, kuin hyötyä. Kannattaa siis suosia "perus" [Component](https://reactjs.org/docs/react-component.html)-luokkaa komponenttien määrittelyssä
- API-kutsut on abstraktoitu hyvin omiin palveluihinsa
- Pyri välttämätään inline-tyylejä, eli tyylien määrittelyä `style`-propin kautta. Sen sijaan määrittele tyylit tyylitiedostoissa ja käytä sopivia luokkavalitsimia `className` propin kautta. [Css-moduulien](https://github.com/css-modules/css-modules) käyttö tekee tyylien määrittelemisestä ja käytöstä helppoa
- Luokka-komponenttien lisäksi kannattaa kokeilla funktionaalisten-komponenttien käyttöä. Niiden avulla pääsee hyödyntämään [hook APIa](https://reactjs.org/docs/hooks-reference.html)
- Lomakkeiden tilanhallinta on hoidettu melko siististi, mutta kun lomakkeen koko kasvaa tai sen logiikka monimutkaistuu, on usein kätevää käyttää jotain lomakkeen tilanhallinnan hoitavaa kirjastoa, kuten [Formik](https://jaredpalmer.com/formik)
- [Promise.all](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all)-metodin avulla voidaan muodostaa monesta promisesta promise, joka resolvaantuu kaikkien saatujen promiseiden resolvautuessa. Esim. [tämän](https://github.com/apndx/ScentGraph/blob/master/src/client/pages/show-scents/show-scents.tsx#L69) koodin saisi muotoon:

```javascript
const [scentsResponse, categoryResponse /* ... */] = await Promise.all([
  getAll("scents"),
  getAll("category"),
  // ...
]);
```

Tällä hetkellä kutsut suoritetaan _peräkkäin_. `Promise.all`-metodin kanssa kutsut suoritetaan _rinnakkain_

- Myös backend-puolen koodi on selkeästi organisoitua, hienoa!
- Reittien käsittelijöiden ainaisista `try { ... } catch (e) { next(e) }`-lohkoista pääsee helposti eroon [express-async-errors](https://www.npmjs.com/package/express-async-errors)-kirjaston avulla

## Kokonaisuus

- Sovellus on suurimmilta osin erittäin käyttäjäystävällinen ja toiminallisuudessa ei ole erityisiä puutteita. Visualisointi on toteutettu erittäin hyvin
- Olet käyttänyt monipuolisesti eri teknologioita ja projekti osoittaa erittäin laajaa osaamista eri osa-alueilta. Itse koodin sisäinen laatu on melko korkea, ainoastaan pienelle hienosäädölle on tarvetta

**Comment by apndx** [comment]
Kiitokset palautteesta, tässä tuli paljonkin itselle uusia asioita joita ottaa kesän aikana kokeiluun :)
